"""Optimization prototypes for TIDE."""

from .cgnr import cgnr_solve
from .first_order import nlcg_minimize, steepest_descent_minimize
from .lbfgs import lbfgs_minimize
from .truncated_newton import truncated_newton_minimize
from .types import (
    CGNROptions,
    CGNRResult,
    CGNRTraceEntry,
    FLAG_CONV,
    FLAG_DES,
    FLAG_FAIL,
    FLAG_GRAD,
    FLAG_HESS,
    FLAG_INIT,
    FLAG_NSTE,
    FLAG_PREC,
    HessianVectorProduct,
    LBFGSOptions,
    NLCGOptions,
    Objective,
    OptimizerOptions,
    OptimizerResult,
    OptimizerTraceEntry,
    Preconditioner,
    SteepestDescentOptions,
    TruncatedNewtonOptions,
    LineSearchMethod,
)

__all__ = [
    "FLAG_CONV",
    "FLAG_DES",
    "FLAG_FAIL",
    "FLAG_GRAD",
    "FLAG_HESS",
    "FLAG_INIT",
    "FLAG_NSTE",
    "FLAG_PREC",
    "CGNROptions",
    "CGNRResult",
    "CGNRTraceEntry",
    "HessianVectorProduct",
    "LBFGSOptions",
    "NLCGOptions",
    "Objective",
    "OptimizerOptions",
    "OptimizerResult",
    "OptimizerTraceEntry",
    "Preconditioner",
    "SteepestDescentOptions",
    "TruncatedNewtonOptions",
    "LineSearchMethod",
    "cgnr_solve",
    "lbfgs_minimize",
    "nlcg_minimize",
    "steepest_descent_minimize",
    "truncated_newton_minimize",
]
