"""Intentional public API snapshot; additions require a documented review."""

import tide


EXPECTED_PUBLIC_NAMES = {
    "BackendPreference",
    "BatchedModel2D",
    "BatchedModel3D",
    "Born3D",
    "BornTM",
    "Callback",
    "CallbackState",
    "ComputeMode",
    "DebyeDispersion",
    "Dimension",
    "FallbackPolicy",
    "Field2DLike",
    "Field3DLike",
    "Location2D",
    "Location3D",
    "MatrixF32",
    "Maxwell3D",
    "MaxwellTM",
    "Model2D",
    "Model2DLike",
    "Model3D",
    "Model3DLike",
    "ReceiverData",
    "ReceiverLocation2D",
    "ReceiverLocation3D",
    "RuntimeOptions",
    "SimulationPlan",
    "SourceLocation2D",
    "SourceLocation3D",
    "StorageMode",
    "StorageOptions",
    "TM2DLinearizationContext",
    "VectorF32",
    "WaveletBatch",
    "born3d",
    "borntm",
    "callbacks",
    "cfl",
    "cfl_condition",
    "compile_simulation_plan",
    "core",
    "create_callback_state",
    "create_or_pad",
    "downsample",
    "downsample_and_movedim",
    "linearize_maxwelltm",
    "maxwell",
    "maxwell3d",
    "maxwell3d_hvp",
    "maxwelltm",
    "maxwelltm_hvp",
    "normalize_backend_request",
    "optim",
    "padding",
    "resampling",
    "reverse_pad",
    "ricker",
    "runtime_typecheck",
    "select_backend",
    "staggered",
    "upsample",
    "utils",
    "validate_freq_taper_frac",
    "validate_model_gradient_sampling_interval",
    "validate_time_pad_frac",
    "validation",
    "wavelets",
    "workflow",
    "zero_interior",
}


def test_public_api_is_explicit() -> None:
    assert set(tide.__all__) == EXPECTED_PUBLIC_NAMES
    assert all(hasattr(tide, name) for name in tide.__all__)
