"""TIDE: differentiable electromagnetic modeling and inversion."""

from . import (
    callbacks,
    cfl,
    core,
    maxwell,
    optim,
    padding,
    resampling,
    staggered,
    utils,
    validation,
    wavelets,
    workflow,
)
from .callbacks import Callback, CallbackState, create_callback_state
from .cfl import cfl_condition
from .core import BackendPreference, FallbackPolicy, StorageMode, StorageOptions
from .dispersion import DebyeDispersion
from .maxwell import (
    Acquisition,
    CPML,
    Discretization,
    EM3DState,
    EMDirection,
    EMGradient,
    EMModel,
    ExecutionOptions,
    Experiment,
    ForwardResult,
    LinearizedMaxwell3D,
    LinearizedMaxwellTM,
    Maxwell3D,
    MaxwellTM,
    Observers,
    SourceConvention,
    TMState,
    TangentResult,
)
from .padding import create_or_pad, reverse_pad, zero_interior
from .resampling import downsample, downsample_and_movedim, upsample
from .typing import (
    BatchedModel2D,
    BatchedModel3D,
    Field2DLike,
    Field3DLike,
    Location2D,
    Location3D,
    MatrixF32,
    Model2D,
    Model2DLike,
    Model3D,
    Model3DLike,
    ReceiverData,
    ReceiverLocation2D,
    ReceiverLocation3D,
    SourceLocation2D,
    SourceLocation3D,
    VectorF32,
    WaveletBatch,
    runtime_typecheck,
)
from .validation import (
    validate_freq_taper_frac,
    validate_model_gradient_sampling_interval,
    validate_time_pad_frac,
)
from .wavelets import ricker

__all__ = [
    "Acquisition",
    "BatchedModel2D",
    "BatchedModel3D",
    "BackendPreference",
    "CPML",
    "Callback",
    "CallbackState",
    "DebyeDispersion",
    "Field2DLike",
    "Field3DLike",
    "Discretization",
    "EM3DState",
    "EMDirection",
    "EMGradient",
    "EMModel",
    "ExecutionOptions",
    "Experiment",
    "Location2D",
    "Location3D",
    "MatrixF32",
    "Model2D",
    "Model2DLike",
    "Model3D",
    "Model3DLike",
    "ReceiverData",
    "ReceiverLocation2D",
    "ReceiverLocation3D",
    "SourceLocation2D",
    "SourceLocation3D",
    "VectorF32",
    "WaveletBatch",
    "FallbackPolicy",
    "ForwardResult",
    "LinearizedMaxwell3D",
    "LinearizedMaxwellTM",
    "Maxwell3D",
    "MaxwellTM",
    "Observers",
    "SourceConvention",
    "StorageMode",
    "StorageOptions",
    "TMState",
    "TangentResult",
    "callbacks",
    "cfl",
    "cfl_condition",
    "core",
    "create_callback_state",
    "create_or_pad",
    "downsample",
    "downsample_and_movedim",
    "maxwell",
    "optim",
    "padding",
    "resampling",
    "reverse_pad",
    "ricker",
    "staggered",
    "upsample",
    "utils",
    "validate_freq_taper_frac",
    "validate_model_gradient_sampling_interval",
    "runtime_typecheck",
    "validate_time_pad_frac",
    "validation",
    "wavelets",
    "workflow",
    "zero_interior",
]

__version__ = "0.1.0"
